all:
	mkdir -p tio_iot/tio
	cp ../../jkii/src/*.c tio_iot/tio
	cp ../../jkii/include/*.h tio_iot/tio
	cp ../../jkii/libs/jsmn/*.c tio_iot/tio
	cp ../../jkii/libs/jsmn/*.h tio_iot/tio
	cp ../../khc/src/*.c tio_iot/tio
	cp ../../khc/src/*.h tio_iot/tio
	cp ../../khc/include/*.h tio_iot/tio
	cp ../../kii/*.c tio_iot/tio
	cp ../../kii/*.h tio_iot/tio
	cp ../../kii/include/*.h tio_iot/tio
	cp ../*.c tio_iot/tio
	cp ../*.h tio_iot/tio
	cp ../include/*.h tio_iot/tio
	cp ./*.c tio_iot
	cp ./*.h tio_iot
	cp ./tio_iot.mk tio_iot

clean:
	rm -rf tio_iot

.PHONY: all
