package com.kii.app.youwill.iap.server.dao.impl;

/**
 * Created by ethan on 14-8-26.
 */
public enum AlipayErrorCode {



		TRADE_NOT_EXIST,ILLEGAL_SIGN,ILLEGAL_DYN_MD5_KEYILLEGAL_ENCRYPT,ILLEGAL_ARGUMENT,ILLEGAL_ENCRYPT,

		ILLEGAL_SERVICE,ILLEGAL_USER,ILLEGAL_PARTNER,ILLEGAL_EXTERFACE,ILLEGAL_PARTNER_EXTERFACE,

		ILLEGAL_SECURITY_PROFILE,ILLEGAL_AGENT,ILLEGAL_SIGN_TYPE,ILLEGAL_CHARSET,ILLEGAL_CLIENT_IP,


		HAS_NO_PRIVILEGE,ILLEGAL_DIGEST_TYPE,ILLEGAL_DIGEST,ILLEGAL_FILE_FORMAT,ILLEGAL_ENCODING

}
