# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'YanKon' do
pod "AMSlideMenu", "~> 1.5.3"
pod 'FMDB'
pod 'KxMenu', '~> 1'
pod 'M13Checkbox', '~> 1.1.2'
pod 'CocoaAsyncSocket', '~> 7.4.1'
pod 'Reachability', '~> 3.2'
end

