#!/bin/sh
# Compile the following libs


sed 's/TOOL_GNU = 0/TOOL_GNU = 1/' ../tool_chain.def > temp
mv -f temp ../tool_chain.def

cd ../../Src/Boot
make clean;make;
if [ $? -ne 0 ]; then
	exit 1
fi
cd -

cd ../../Src/Drivers/cpu
make clean;make;
if [ $? -ne 0 ]; then
	exit 1
fi
cd -

cd ../../Src/Drivers/irq
make clean;make;
if [ $? -ne 0 ]; then
	exit 1
fi
cd -

cd ../../Src/Drivers/timer
make clean;make;
if [ $? -ne 0 ]; then
	exit 1
fi
cd -

cd ../../Src/Drivers/efuse
make clean;make;
if [ $? -ne 0 ]; then
	exit 1
fi
cd -

cd ../../Src/Drivers/flash
make clean;make;
if [ $? -ne 0 ]; then
	exit 1
fi
cd -

cd ../../Src/Drivers/gpio
make clean;make;
if [ $? -ne 0 ]; then
	exit 1
fi
cd -

cd ../../Src/Drivers/hspi
make clean;make;
if [ $? -ne 0 ]; then
	exit 1
fi
cd -

cd ../../Src/Drivers/spi
make clean;make;
if [ $? -ne 0 ]; then
	exit 1
fi
cd -

cd ../../Src/Drivers/uart
make clean;make;
if [ $? -ne 0 ]; then
	exit 1
fi
cd -

cd ../../Src/Drivers/litepoint
make clean;make;
if [ $? -ne 0 ]; then
	exit 1
fi
cd -

cd ../../Src/Drivers/dma
make clean;make;
if [ $? -ne 0 ]; then
	exit 1
fi
cd -

cd ../../Src/Network/lwip1.4.1
make clean;make;
if [ $? -ne 0 ]; then
	exit 1
fi
cd -

cd ../../Src/Network/api
make clean;make;
if [ $? -ne 0 ]; then
	exit 1
fi
cd -

cd ../../Src/Os/uCOS-II
make clean;make;
if [ $? -ne 0 ]; then
	exit 1
fi
cd -

cd ../../Src/Os/OS_ports
make clean;make;
if [ $? -ne 0 ]; then
	exit 1
fi
cd -

cd ../../Src/Wlan/
make clean;make;
if [ $? -ne 0 ]; then
	exit 1
fi
cd -

cd ../../Src/Sys
make clean;make;
if [ $? -ne 0 ]; then
	exit 1
fi
cd -

cd ../../Src/Common/mem
make clean;make;
if [ $? -ne 0 ]; then
	exit 1
fi
cd -

cd ../../Src/Common/utils
make clean;make;
if [ $? -ne 0 ]; then
	exit 1
fi
cd -

cd ../../Src/Common/Params
make clean;make;
if [ $? -ne 0 ]; then
	exit 1
fi
cd -

cd ../../Src/Common/fwup
make clean;make;
if [ $? -ne 0 ]; then
	exit 1
fi
cd -


cd ../../App/dhcpserver
make clean;make;
if [ $? -ne 0 ]; then
	exit 1
fi
cd -

cd ../../App/dnsserver
make clean;make;
if [ $? -ne 0 ]; then
	exit 1
fi
cd -

#cd ../../App/iperf
#make clean;make;
#if [ $? -ne 0 ]; then
#	exit 1
#fi
#cd -

cd ../../App/httpclient
make clean;make;
if [ $? -ne 0 ]; then
	exit 1
fi
cd -

cd ../../App/wm_atcmd
make clean;make;
if [ $? -ne 0 ]; then
	exit 1
fi
cd -

cd ../../App/oneshotconfig
make clean;make;
if [ $? -ne 0 ]; then
	exit 1
fi
cd -

cd ../../App/demo
make clean;make;
if [ $? -ne 0 ]; then
	exit 1
fi
cd -

make clean;make
