var searchData=
[
  ['task_20callbacks_0',['task callbacks',['../index.html#autotoc_md3',1,'Task callbacks'],['../index.html#autotoc_md15',1,'Task callbacks.']]],
  ['task_20callbacks_20socket_20callbacks_1',['Task callbacks, socket callbacks',['../index.html#autotoc_md25',1,'']]],
  ['task_20continue_20callback_2',['Task continue callback',['../index.html#autotoc_md5',1,'']]],
  ['task_20creation_3',['Task creation',['../index.html#autotoc_md4',1,'']]],
  ['task_20exit_20callback_4',['Task exit callback',['../index.html#autotoc_md6',1,'']]],
  ['task_20management_5',['Asynchronous task management',['../index.html#autotoc_md32',1,'']]],
  ['task_5fstate_6',['task_state',['../../../kii/html/structkii__mqtt__task__info.html#a10dd846ce66170de1a124dc32cdc46b8',1,'kii_mqtt_task_info::task_state'],['../structtio__handler__task__info__t.html#aec172492cb54a0cc922faf12b7a208d4',1,'tio_handler_task_info_t::task_state']]],
  ['tasks_20executed_20by_20tt_20tio_5fhandler_5ft_20tt_7',['Tasks executed by &lt;tt&gt;tio_handler_t&lt;/tt&gt;.',['../index.html#autotoc_md33',1,'']]],
  ['tasks_20executed_20by_20tt_20tio_5fupdater_5ft_20tt_8',['Tasks executed by &lt;tt&gt;tio_updater_t&lt;/tt&gt;.',['../index.html#autotoc_md34',1,'']]],
  ['timeout_9',['Set-up MQTT socket timeout.',['../index.html#autotoc_md18',1,'']]],
  ['tio_10',['tio',['../index.html',1,'']]],
  ['tio_5faction_5ferr_5ft_11',['tio_action_err_t',['../structtio__action__err__t.html',1,'']]],
  ['tio_5faction_5fresult_5fdata_5ft_12',['tio_action_result_data_t',['../structtio__action__result__data__t.html',1,'']]],
  ['tio_5faction_5ft_13',['tio_action_t',['../structtio__action__t.html',1,'']]],
  ['tio_5faction_5fvalue_5ft_14',['tio_action_value_t',['../structtio__action__value__t.html',1,'']]],
  ['tio_5fhandler_5finit_20tt_20call_15',['&lt;tt&gt;tio_handler_init&lt;/tt&gt; call',['../index.html#autotoc_md12',1,'']]],
  ['tio_5fhandler_5fset_5fapp_20tt_20call_16',['&lt;tt&gt;tio_handler_set_app&lt;/tt&gt; call',['../index.html#autotoc_md13',1,'']]],
  ['tio_5fhandler_5ft_17',['tio_handler_t',['../structtio__handler__t.html',1,'']]],
  ['tio_5fhandler_5ft_20tt_18',['tio_handler_t tt',['../index.html#autotoc_md33',1,'Tasks executed by &lt;tt&gt;tio_handler_t&lt;/tt&gt;.'],['../index.html#autotoc_md1',1,'Use &lt;tt&gt;tio_handler_t&lt;/tt&gt;']]],
  ['tio_5fhandler_5ft_20tt_20instance_19',['Set-up &lt;tt&gt;tio_handler_t&lt;/tt&gt; instance',['../index.html#autotoc_md11',1,'']]],
  ['tio_5fhandler_5ftask_5finfo_5ft_20',['tio_handler_task_info_t',['../structtio__handler__task__info__t.html',1,'']]],
  ['tio_5fupdater_5ft_21',['tio_updater_t',['../structtio__updater__t.html',1,'']]],
  ['tio_5fupdater_5ft_20tt_22',['tio_updater_t tt',['../index.html#autotoc_md34',1,'Tasks executed by &lt;tt&gt;tio_updater_t&lt;/tt&gt;.'],['../index.html#autotoc_md23',1,'Use &lt;tt&gt;tio_updater_t&lt;/tt&gt;']]],
  ['tio_5fupdater_5ft_20tt_20instance_23',['Set-up &lt;tt&gt;tio_updater_t&lt;/tt&gt; instance',['../index.html#autotoc_md29',1,'']]],
  ['tokens_24',['tokens',['../../../jkii/html/structjkii__resource__t.html#adfd476e8fc0cfba750e837734287cb8a',1,'jkii_resource_t']]],
  ['tokens_5fnum_25',['tokens_num',['../../../jkii/html/structjkii__resource__t.html#a831a9295c6f4eecfc2889e5792bd2953',1,'jkii_resource_t']]],
  ['topic_26',['topic',['../../../kii/html/structkii__mqtt__endpoint__t.html#a541920b531df8bb20f58e1dd7c0a3c81',1,'kii_mqtt_endpoint_t']]],
  ['topic_5fname_27',['topic_name',['../../../kii/html/structkii__topic__t.html#a2ea6785013916b715b151da705a5d54a',1,'kii_topic_t']]],
  ['tt_20tio_5fhandler_5finit_20tt_20call_28',['&lt;tt&gt;tio_handler_init&lt;/tt&gt; call',['../index.html#autotoc_md12',1,'']]],
  ['tt_20tio_5fhandler_5fset_5fapp_20tt_20call_29',['&lt;tt&gt;tio_handler_set_app&lt;/tt&gt; call',['../index.html#autotoc_md13',1,'']]],
  ['tt_20tio_5fhandler_5ft_20tt_30',['tt tio_handler_t tt',['../index.html#autotoc_md33',1,'Tasks executed by &lt;tt&gt;tio_handler_t&lt;/tt&gt;.'],['../index.html#autotoc_md1',1,'Use &lt;tt&gt;tio_handler_t&lt;/tt&gt;']]],
  ['tt_20tio_5fhandler_5ft_20tt_20instance_31',['Set-up &lt;tt&gt;tio_handler_t&lt;/tt&gt; instance',['../index.html#autotoc_md11',1,'']]],
  ['tt_20tio_5fupdater_5ft_20tt_32',['tt tio_updater_t tt',['../index.html#autotoc_md34',1,'Tasks executed by &lt;tt&gt;tio_updater_t&lt;/tt&gt;.'],['../index.html#autotoc_md23',1,'Use &lt;tt&gt;tio_updater_t&lt;/tt&gt;']]],
  ['tt_20tio_5fupdater_5ft_20tt_20instance_33',['Set-up &lt;tt&gt;tio_updater_t&lt;/tt&gt; instance',['../index.html#autotoc_md29',1,'']]],
  ['ttl_34',['ttl',['../../../kii/html/structkii__mqtt__endpoint__t.html#ad07b60aae4d353b09eac993a725f353e',1,'kii_mqtt_endpoint_t']]],
  ['type_35',['type',['../structtio__action__value__t.html#ae37aa5cf6246ce83845320168a92e832',1,'tio_action_value_t::type'],['../../../jkii/html/structjkii__field__t.html#ab2b34feaeed6c4fc6364e3195cf1f841',1,'jkii_field_t::type']]]
];
